version: "3.9"
services:
  # Fake HTTPS Server
  fake.ssl:
    container_name: nginx
    #build: .
    image: nginx
    ports:
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./public.crt:/etc/nginx/ssl/public.crt
      - ./private.key:/etc/nginx/ssl/private.key

  # SpringBoot APP
  spring:
    container_name: spring
    image: yoanyo/hello-world
    ports:
      - 8080:8080
    environment:
      SERVICE_BINDING_ROOT: /bindings
    volumes:
      - ../bindings/ca-certificates:/bindings/ca-certificates
