#
# Regular java image from source code
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-spring-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-spring-app
  template:
    metadata:
      labels:
        app: my-spring-app
    spec:
      containers:
        - name: my-spring-app
          image: yoanyo/hello-world:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: SERVICE_BINDING_ROOT
              value: "/mnt/platform/bindings"
          volumeMounts:
            - name: ca-certs
              mountPath: /mnt/platform/bindings/ca-certificates
              readOnly: true
      volumes:
        - name: ca-certs
          secret:
            secretName: tutorial-certificates
            items:
            - key: "superusercom.crt"
              path: "superusercom.crt"
            - key: "type"
              path: "type"
---
apiVersion: v1
kind: Service
metadata:
  name: my-spring-app-service
spec:
  selector:
    app: my-spring-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
