#
# Native image from source code
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-spring-app-native
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-spring-app-native
  template:
    metadata:
      labels:
        app: my-spring-app-native
    spec:
      containers:
        - name: my-spring-app-native
          image: yoanyo/hello-world-native:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
---
apiVersion: v1
kind: Service
metadata:
  name: my-spring-app-native-service
spec:
  selector:
    app: my-spring-app-native
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
