#
# Regular image from source inside a source image from scratch
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-spring-app-source
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-spring-app-source
  template:
    metadata:
      labels:
        app: my-spring-app-source
    spec:
      containers:
        - name: my-spring-app-source
          image: yoanyo/hello-world-source:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
---
apiVersion: v1
kind: Service
metadata:
  name: my-spring-app-source-service
spec:
  selector:
    app: my-spring-app-source
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
