apiVersion: v1
kind: Secret
metadata:
  name: tutorial-nginx-config
stringData:
  nginx.conf: |
    events {
        worker_connections 1024;
    }
    http {
        server {
            listen 443 ssl;
            server_name localhost;

            ssl_certificate /etc/nginx/ssl/public.crt;
            ssl_certificate_key /etc/nginx/ssl/private.key;

            location / {
                root /usr/share/nginx/html;
                index index.html;
            }
        }
    }  
  private.key: |
    -----BEGIN PRIVATE KEY-----
    MIIJQwIBADANBgkqhkiG9w0BAQEFAASCCS0wggkpAgEAAoICAQDsTnqPWCZeESjH
    mJvRgYFxVWhEks36qfw/tn3VnMMR72QRBx6ECFZUsbderP4wL2Pp45MXxY9EEjGP
    4R1d5/FCXi4zMU/yktasJx0YfOxJV+KQdSf8HerlTBg30ielAsj3Z4HtK8fnEyL2
    IjfmiHs6Z1IsT5X2FOjwFyh6dwk0QEiNELCl1q57j2j4HpU3BHcgCoXOR4ksvtyZ
    z2h0XZh6kALX2Y3Ygi/0YjdyCPBB2tQ5dOAfPFpKDwgKrIytq8D6j+p4LHbJq07p
    dLnkMgS6VU1a1hmpg21jhV3L2b++Sltzi6TIh3xRCFi9POy6esKVXvn40Jn8Iph+
    K6tdFuNI9NOi8OAHYi7GBFk+1c4FtlEUa1sl22CqQ3vfoBHX+582S2rkPwHoNBwI
    deIiEJ1xqc9KOjQ68bL4AO1Glbfn8DVx7D6O2uHUYPO0Yp3xnaTAk/cYPpiqHilT
    /XrPX+9aDHu/LcergyZG8hbShok3WZF0Vq0UorbXBrba/id/Tor4rFZbHaxy+kDk
    X5cZ+r3EWui2XHM2qROISxWOTw8e+7WQOSiy37NqVspTjKESikMZaEDaMH8012XI
    rwGjK7aLoePiTVjcmPL1Gdk3Iif16N1LrQ8vN9U0bK/QJobzYsw63spHQKVMXvo2
    pgFK7rrCkPcSQreITQSMwDyI5PxH2QIDAQABAoICAQDInR+jjjyUY5DxUngGdyHD
    a7SnctJ32dQS6wUNUpaxJUEYy6h2gvV31aBNOiRaGAGE0PVRmyEzsxZshbr+vCiw
    JXCneVfcIhkp8dLbtUKMSZZI+Y1GlseSfvWYfku15RVkJHXDOgXuAOsPdqFqj7e+
    L3UttSskzT+shJySy3f+6gwt5ltxjz52G5wL+TrIiHvxsb1DEKw+VpLF6bVOBR+r
    /ZLMWR/5DR1VJgTYRQpjfjnpxXV4Ty5/7R7woOiVkFi233M5LtZyA4Ns4vHl7yjg
    YAbZ9SW4KaG2ecTViTklfc8B2y28KHm7+ZAMqCp5bjq/wPAK8l2oFl7Lzpse3o15
    Au7GQhAh5jQUtbzX0O0nKcH0Ex63CGl+8M6YUv6HGoUYvpcyOXjeg+Ao0s1QQxlc
    rocUAlbIFAHB0upq2TLvu6s9FC3c0VD8Jj26PPS8rtml2J1qkRvTqz84AaZO+eti
    SKyYSL1kCzgCkQezGNd6cnjXGgIacr/5xGJQpIiqX8nBPacNBT2Mp58shnrD9pEb
    x3NXKEuEfWKpZRHEFh7DiLhLfswyT63PGi6Jj/MC68f8eRi23nKRjekYAVV82TmG
    v3udo7/hHVFT1z1dKPPCmq5HdjAu3W5c3Qd9zZ/zoWIJm0lN8HYExaEPHYSRcL7n
    zTZad9I3K+ogJlMhAtqeeQKCAQEA9/rj5w3qYtL5ETDhI2hGY2mXBo0jOAysz2tw
    y19F8eJB0EN2Gp202BeI3CkrG9MlXEhwo9JdLMDDBmMXVpPAV+dqcZt74h0Uphwe
    gcSab8qXz4fcJ0u95gBfknndsb1JnHPAH6Aeo1yD5BE+JAXPzfGaHsTSlTch0rwS
    vSScFyECEv3dcQVrQiCs/AU85GSJkZ8CAX0/tI04D/zidtAKjCvtiFdTMEWHXfnz
    cWXXluM801Eg4V9OsABN+jmPiazqS3m6+OyjtEyACF2XqzRoa/mSIB951HFd45kj
    uS6PB3aWs9jMUT/dQpI2Ds5PQapbuBQwWdUObdVah+SuZ7/MPwKCAQEA8/LwmSxO
    PNlHkAztOhTgcrYs2+9EUbNr3JiDEZXlQADfJscrg5y7DcRWI7YGM91k2JNFSP8D
    RkIaO8rgzGXwHHk9b2DSZLs6Gy6ZwjEFqql8HvYbqNfKrlwo9/RckItAnJNjlbKC
    4wbwqn9KC7ktUolPArirrF29VhVHv57Md1eNyXtWS9dXyur2M32k342IvveIs3mc
    GwDpoplXonRtamA7sWrdH3xSTUsLOMJREci2RHc1ywSyaCsxKxR7oBgdZh8TZCbZ
    2uTJ5JRBeHAbw2TS5p1l32Bw5f5pjsmoa51xTzuuqZ/O2pBzz33I2G7hM3bW1qbU
    w0SG44dLa6JF5wKCAQBgmdHSHm+iE8GG2t25Z1OUQnvcx3piyT1AiAAmmXSr55Hv
    yXfmomziiTh9W2Q5sKUrL+UBTF+ToXvXrx5WUbRqCfJDU2iNCvsSQn3321i2F9vP
    soMmo7DUOm0AqIyeQri8Q7MiHsQQq2eNntHwQntTJLz/I3lNO27novBB0lMkB23B
    bDepYY0I86Wvf3LbHfchTSoA3oPEmAaw47hsxFp3hF1B8ZKsiUlUaJxXHm8/jkIR
    p9cBNJl4ooW95lJuNXgH8uHNOpIDGJH/sEX3IbFT7qLn9JsHESqcEPoDl4mMRLws
    T1Y4iIJu/nokhmYFlJGqQeMb+41lZ+meao0uSV8NAoIBAQCIGUqX+jrwAbzGJiAX
    nlwWQ4LFdTilaDdODBxbrEgJLDNTPB0PwVoudRIlvEC7oNHJbmhiMDvQb8KZBzfh
    cSHDkPRwdhELN9VUIuyPhbAGpaXk1CNcUH/4RNxqcX9O+RGkCSqu8rfJFy8fwAI8
    hiQ9/vMArqzAbk/afebYhizGjCdDeDcN+uc1A182HOvl+N2IxSsUDk3EVv8BwxE8
    Rj5g8a177wXMshxsmOh60xZNmK/vhJ6TVFyAd1BoG3ZZO/ry5XV5E5/JWok0qG3a
    Vpl2qoJrPPb/55s1BXo4ulLnLyBvNvncEpdiIuMpqKBr93hWsP9tJAhhpJKoz+uI
    8jCTAoIBAGbzqYvQBNfcqFj0fVPxQLVoIQq8JbLgMNvz1F61Y/5xfXur416h5Z0A
    HR3wxKXlNHLDVaV4tmgyiVZjnU2UcnAKYny1w/I5HmJ+7HiruoDfuPQivf+A2+jc
    WlHCh7garF9ylnmXvwzkNM4L687dgNZqIWs3hmIYUUucOmBcIcgTkeq7UpPw8qPs
    xTcyhGRTZTi4Y/3tce6M3N+GeRKzvI2dHFVuQq/N6Vb89HPzPEso9jvmtQCUpvZ/
    y8Xh2JnzJykJcgZyQds/ijz8UpLWSWLdHXtvruszyb7JSaZjWW9+pLqIwNhSa4Qb
    +k7TQ7459VSYshruHFejcNoMCsUROvs=
    -----END PRIVATE KEY-----
  public.crt: |
    -----BEGIN CERTIFICATE-----
    MIIFcDCCA1gCCQDE8OTQQlr0sjANBgkqhkiG9w0BAQsFADB6MQswCQYDVQQGEwJY
    WDESMBAGA1UECAwJU3RhdGVOYW1lMREwDwYDVQQHDAhDaXR5TmFtZTEUMBIGA1UE
    CgwLQ29tcGFueU5hbWUxGzAZBgNVBAsMEkNvbXBhbnlTZWN0aW9uTmFtZTERMA8G
    A1UEAwwIZmFrZS1zc2wwHhcNMjMxMTIxMTY0MjAzWhcNMzMxMTE4MTY0MjAzWjB6
    MQswCQYDVQQGEwJYWDESMBAGA1UECAwJU3RhdGVOYW1lMREwDwYDVQQHDAhDaXR5
    TmFtZTEUMBIGA1UECgwLQ29tcGFueU5hbWUxGzAZBgNVBAsMEkNvbXBhbnlTZWN0
    aW9uTmFtZTERMA8GA1UEAwwIZmFrZS1zc2wwggIiMA0GCSqGSIb3DQEBAQUAA4IC
    DwAwggIKAoICAQDsTnqPWCZeESjHmJvRgYFxVWhEks36qfw/tn3VnMMR72QRBx6E
    CFZUsbderP4wL2Pp45MXxY9EEjGP4R1d5/FCXi4zMU/yktasJx0YfOxJV+KQdSf8
    HerlTBg30ielAsj3Z4HtK8fnEyL2IjfmiHs6Z1IsT5X2FOjwFyh6dwk0QEiNELCl
    1q57j2j4HpU3BHcgCoXOR4ksvtyZz2h0XZh6kALX2Y3Ygi/0YjdyCPBB2tQ5dOAf
    PFpKDwgKrIytq8D6j+p4LHbJq07pdLnkMgS6VU1a1hmpg21jhV3L2b++Sltzi6TI
    h3xRCFi9POy6esKVXvn40Jn8Iph+K6tdFuNI9NOi8OAHYi7GBFk+1c4FtlEUa1sl
    22CqQ3vfoBHX+582S2rkPwHoNBwIdeIiEJ1xqc9KOjQ68bL4AO1Glbfn8DVx7D6O
    2uHUYPO0Yp3xnaTAk/cYPpiqHilT/XrPX+9aDHu/LcergyZG8hbShok3WZF0Vq0U
    orbXBrba/id/Tor4rFZbHaxy+kDkX5cZ+r3EWui2XHM2qROISxWOTw8e+7WQOSiy
    37NqVspTjKESikMZaEDaMH8012XIrwGjK7aLoePiTVjcmPL1Gdk3Iif16N1LrQ8v
    N9U0bK/QJobzYsw63spHQKVMXvo2pgFK7rrCkPcSQreITQSMwDyI5PxH2QIDAQAB
    MA0GCSqGSIb3DQEBCwUAA4ICAQBsvt/W6G54BPWdbj1SB+1zILgblcMnX4aohS5f
    934CsGEulbbcnwmQKApH8hNNJ+XWHq6e9+URLNuHYA2r79H3EOFMvyy/RjtpK5Fv
    k2kGgseMpbDuaP3nqXVnA4nbb/LtLUOjGhH/XxEcqhGeWsKZz+ck+jReHCj6x3ZR
    hAxkEatBXYSTcVriVtYKRZsL52RBUTJKnRGfUgcRJk37fvDgSNUQsRuQxuz28GgG
    lsZaoFgphQXuAvzpI12W0YPLacRX/h6beMYOgGJBkK8iSbLuRUujFSlcwejqy0z9
    CukxV6pgPdWqHBR+a+KLKwMm0FT4+Yl29+/OBbKF6b+rd7MK8FxNKV+k0EaJ7WK7
    atepC1yvelXdsAFhSVXneQ11+Kdn7+p9zrBRkTN/+gEF3pG6/kIu7mvrZpr8gIZd
    7EUEm7GdcRELHwb8ym2l+8jlPa/2whI/Kv5Cun4lMzHA6pA74CG8DTbFn9uJIXYS
    SHGyjqGmJC7Iw4jysfFcvx3RwFkT/XZkvdngJ5e6lK8dcVpDP0sfuotjCtc9f1fG
    RToqJIU6XV+nSWvE9oMnJ2FLYOhSz7AMorpHs07D7x6dQMSHaLwqCfJsbQBafy23
    6ZarZw/JQVXxIponIMKNCR1VNiAVVDT7Q4NOiSwp4Vza21L0SGXY4ryujeAUCKnd
    fv1r5w==
    -----END CERTIFICATE-----
---
apiVersion: v1
kind: Secret
metadata:
  name: tutorial-settings
type: service.binding/maven
stringData:
  type: maven
  provider: sample
  settings.xml: |
    <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 https://maven.apache.org/xsd/settings-1.0.0.xsd">
        <profiles>
            <profile>
                <id>profile-test</id>
                <properties>
                    <tomcat.version>9.0.80</tomcat.version>
                </properties>
            </profile>
        </profiles>
    </settings>
---
apiVersion: v1
kind: Secret
metadata:
  name: tutorial-certificates
type: service.binding/ca-certificates
stringData:
  type: ca-certificates
  provider: sample
  public.crt: |
    -----BEGIN CERTIFICATE-----
    MIIFcDCCA1gCCQDE8OTQQlr0sjANBgkqhkiG9w0BAQsFADB6MQswCQYDVQQGEwJY
    WDESMBAGA1UECAwJU3RhdGVOYW1lMREwDwYDVQQHDAhDaXR5TmFtZTEUMBIGA1UE
    CgwLQ29tcGFueU5hbWUxGzAZBgNVBAsMEkNvbXBhbnlTZWN0aW9uTmFtZTERMA8G
    A1UEAwwIZmFrZS1zc2wwHhcNMjMxMTIxMTY0MjAzWhcNMzMxMTE4MTY0MjAzWjB6
    MQswCQYDVQQGEwJYWDESMBAGA1UECAwJU3RhdGVOYW1lMREwDwYDVQQHDAhDaXR5
    TmFtZTEUMBIGA1UECgwLQ29tcGFueU5hbWUxGzAZBgNVBAsMEkNvbXBhbnlTZWN0
    aW9uTmFtZTERMA8GA1UEAwwIZmFrZS1zc2wwggIiMA0GCSqGSIb3DQEBAQUAA4IC
    DwAwggIKAoICAQDsTnqPWCZeESjHmJvRgYFxVWhEks36qfw/tn3VnMMR72QRBx6E
    CFZUsbderP4wL2Pp45MXxY9EEjGP4R1d5/FCXi4zMU/yktasJx0YfOxJV+KQdSf8
    HerlTBg30ielAsj3Z4HtK8fnEyL2IjfmiHs6Z1IsT5X2FOjwFyh6dwk0QEiNELCl
    1q57j2j4HpU3BHcgCoXOR4ksvtyZz2h0XZh6kALX2Y3Ygi/0YjdyCPBB2tQ5dOAf
    PFpKDwgKrIytq8D6j+p4LHbJq07pdLnkMgS6VU1a1hmpg21jhV3L2b++Sltzi6TI
    h3xRCFi9POy6esKVXvn40Jn8Iph+K6tdFuNI9NOi8OAHYi7GBFk+1c4FtlEUa1sl
    22CqQ3vfoBHX+582S2rkPwHoNBwIdeIiEJ1xqc9KOjQ68bL4AO1Glbfn8DVx7D6O
    2uHUYPO0Yp3xnaTAk/cYPpiqHilT/XrPX+9aDHu/LcergyZG8hbShok3WZF0Vq0U
    orbXBrba/id/Tor4rFZbHaxy+kDkX5cZ+r3EWui2XHM2qROISxWOTw8e+7WQOSiy
    37NqVspTjKESikMZaEDaMH8012XIrwGjK7aLoePiTVjcmPL1Gdk3Iif16N1LrQ8v
    N9U0bK/QJobzYsw63spHQKVMXvo2pgFK7rrCkPcSQreITQSMwDyI5PxH2QIDAQAB
    MA0GCSqGSIb3DQEBCwUAA4ICAQBsvt/W6G54BPWdbj1SB+1zILgblcMnX4aohS5f
    934CsGEulbbcnwmQKApH8hNNJ+XWHq6e9+URLNuHYA2r79H3EOFMvyy/RjtpK5Fv
    k2kGgseMpbDuaP3nqXVnA4nbb/LtLUOjGhH/XxEcqhGeWsKZz+ck+jReHCj6x3ZR
    hAxkEatBXYSTcVriVtYKRZsL52RBUTJKnRGfUgcRJk37fvDgSNUQsRuQxuz28GgG
    lsZaoFgphQXuAvzpI12W0YPLacRX/h6beMYOgGJBkK8iSbLuRUujFSlcwejqy0z9
    CukxV6pgPdWqHBR+a+KLKwMm0FT4+Yl29+/OBbKF6b+rd7MK8FxNKV+k0EaJ7WK7
    atepC1yvelXdsAFhSVXneQ11+Kdn7+p9zrBRkTN/+gEF3pG6/kIu7mvrZpr8gIZd
    7EUEm7GdcRELHwb8ym2l+8jlPa/2whI/Kv5Cun4lMzHA6pA74CG8DTbFn9uJIXYS
    SHGyjqGmJC7Iw4jysfFcvx3RwFkT/XZkvdngJ5e6lK8dcVpDP0sfuotjCtc9f1fG
    RToqJIU6XV+nSWvE9oMnJ2FLYOhSz7AMorpHs07D7x6dQMSHaLwqCfJsbQBafy23
    6ZarZw/JQVXxIponIMKNCR1VNiAVVDT7Q4NOiSwp4Vza21L0SGXY4ryujeAUCKnd
    fv1r5w==
    -----END CERTIFICATE-----
---
# Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tutorial-service-account
  namespace: default
secrets:
  - name: tutorial-registry-credentials
  - name: tutorial-certificates
  - name: tutorial-settings
imagePullSecrets:
  - name: tutorial-registry-credentials
