# Native image from source code
# Image
apiVersion: kpack.io/v1alpha2
kind: Image
metadata:
  name: tutorial-image-native
  namespace: default
spec:
  tag: yoanyo/hello-world-native
  serviceAccountName: tutorial-service-account
  builder:
    name: java-native-builder
    kind: Builder
  source:
    git:
      url: https://github.com/juanjmerono/hello-world
      revision: main
  build:
    env:
      - name: BP_MAVEN_BUILD_ARGUMENTS
        value: --batch-mode -f pom-spring3.xml --no-transfer-progress package
      - name: BP_NATIVE_IMAGE
        value: "true"
