apiVersion: v1
kind: Secret
metadata:
  name: tutorial-nginx-config
stringData:
  nginx.conf: |
    events {
        worker_connections 1024;
    }
    http {
        server {
            listen 443 ssl;
            server_name localhost;

            ssl_certificate /etc/nginx/ssl/public.crt;
            ssl_certificate_key /etc/nginx/ssl/private.key;

            location / {
                root /usr/share/nginx/html;
                index index.html;
            }
        }
    }  
  private.key: |
    -----BEGIN PRIVATE KEY-----
    MIIJQwIBADANBgkqhkiG9w0BAQEFAASCCS0wggkpAgEAAoICAQDmQCS9f6taTTEy
    w2dtDjb5nefW6fDzcL0aT3P9PqFtK4xLD91DF2xK/+MEia5HuG4c6FXF/RC6vLM6
    LvRf9/smfQaLZ/E6bE2WxnWgtcF6RgTO4FqJQp8er6jEkQyNCS+CPhzbOXwUUc1u
    2GUeQKGVkILyRH6k+zt/PWM1yvv7VS4XZFR9HpfEggNj3SE4q5K57kg4VE3RMY1I
    mHNf9+UNeIu37TI37wABBO3zzTAM3hyoP0xBlg+4r3ZBKW8XzGNpUcR64w+HuF9h
    0t0UN+tMVWKeJ3plSoysgOhIaEuqg6sWf6zQ/6rvxjj97rCPuyDS28O4HFpXs6j4
    vwgcsa037Z+6+km1+3ci3IRdN8IVZoV7zjS4IZrVTGvp9tfSIuhR3KFrTRaiJGsj
    ZttllixmVr0JZSC87p0t/ASmcPrTy75xxBL8hI1uQwjUsxKtjl6tqmd8bQRAfh1n
    JaQeib/7uGRI82K53qaMjjQ9dvJbyeOOw+qJcF6DxI2LPPil9fvmjctEATXWESa7
    ZmeOGqyvzMQRrZL5TXu3o8T+oj4MpZrLrSDJLym2RhYf2GssG1MJankxDAWAbMYM
    /QwfOxVWSExdgPjh2NtJDRgBNluPGdlbOzlwfad7MwGm+s+eNKW5JYWKIigDg+cj
    5rdX367+qLgN7IqRpr5teNUf45683wIDAQABAoICAAepmM9poUU3Dm0XDakWcQPr
    mlyPmoIvfUuT21NRM0QTz+5rj7x82hDA5UgwYMloPNnfbYNSQa1FPF2yVFWhRg1o
    2b/n7KI6GnbrEd0QT2kHTX+o/bpVqj/2LpKkFRvYc2lNMd6l0hhHBKQstWjFU9tL
    XOA9IU3SQo+gdl3C7JHXqtoCb8FeNETI4t3+7O0a4J4pbOPbAl/02zPQRv6pnEjP
    ey7ayPINlR1zkYush23WMnPy71G7cbh+tlvCyjyrg59spjJEvi6RFzOFNfBHUCBR
    Mx/6Rlt6mKXhAFnwhpwdF6N/CjxGVeT23sysldmiq5v4zlGhN+x1QSlOCjISQ6Zp
    rA4/NpEwXaAbTtHG5fB2grdRVAEhXo6DpqZ7sj4heXXuuDIlgKwUwbbpTcF1kQoR
    9HI2vK9x2pGcXHadqTfOrZfPUo4DHNoSl7aE7JngdSc3oJExiNpMTnKywHAJL3i7
    E2dQtemt6R3780z8L/Rbiuko7pOau+80pm3K6Ls9TSkKfUmdX4Ijt/vvvg0J2VU2
    MdaS3l2E1zK3yvzeKGXbOndxO8hKvUbGdHIpJyIF8ptG2mgviYPtAwhpemJc+igN
    1UYCFdrbyXqnlcx7o5r2Ic9nKFWnM3KjEYuCIp05BmEoBXjgZDX0ZjSTQPVdlkjc
    rhPeA7dMmtwjfz+lQTB5AoIBAQD08Q7AxE2qexHw0YFi+RK1c3isX9+tEXgbxoes
    TnUi36SXoUFyqgwzW3T6f68pp8sm8fe6WMJ7ANXLxohC09bc2xuyzk3lgw4jErZo
    719bTwm/2GffpvB2m/GgoluYWVMcSoN+LbY4foK9soNLpwFBLdn3E1GIvtd2Ga88
    ZvoJnXv0MF6wZpdN3MEmnp0T1u9277VhFNjWc/oLtVuxx59iSnZ2MXveTKDla3Xs
    Akm3TG0+tWDvxERYtDIfZ4mIMpk8htkqMO6xHhPwpGZ9suWMIHqCuyTV+hKaQNwi
    drJ8Z24PnZOGukXqIAf4Au+BGpey8eD0VM+S/5EwWhoX72drAoIBAQDwpUrFGsga
    qSRpxUbpmCOfNT7fPZwUUuoixrQP/1kK4WzO52mf38gg+adC2IM1pO14CX50VHUq
    P4/VYkXW19IaRUn8zUUjVzxj1KcTqSOVp5CTI1lSyavqxy4/gOf2CVp9VQBAIDFU
    Xkdt/mO428f9HdrZUEnxxbXc38tpj2yJI1XdhyoFcFgW9uozWCrnzcM1MVnAO+Fo
    vlBvIYSFgCrfCR+bvExu2HIFFhvxqD9YGMb1sOkeSQtsG4wpujNpWLLz589NDgfb
    DVMI6emqNggSvM5L1S1PC65+NFdiIkxdFnspyVb9bbMzK9Jme/5uWW0RXWksX9wY
    5DdxhGVmLEFdAoIBADTu/2QzSCGGlTr428Ba2WszOCnwUjNhqhY+kkVvcysFL9nA
    9JbmHtrecepMu7sB0wpokkPIOMdCR/HQxtPCWhXCmDrNENJ/vwdfXOJSkMX3z8CQ
    8OnJdv/69X3keGz1KNvdUotrL40H8hMyx+MKhV/jm84kc6Ncss2IAXHJQ1HeodIE
    vgHbOemOwoMpFgMamQeYCBeh3LaDu87Z86X44P3p363tRbqlzsOltIc7e1jMgHNj
    2T4XqTmOP6K/yl4PqUQGVFok1wCZ4m9H6ApUJf1ha3hjHzPK5khFqg0cn7f41jUz
    tZURHljZcT9syvuYlp4KXbYPuggniOXtIuR3TV8CggEBAKy/m4sfDKLG5RLgwWUT
    CA9UI8wR6CdW1ikcx0nsnjkHVhq5WMOh24KAdSexUY+C082l0xcjQfCQLGqb31K5
    H2QodVJ68LTL/NgVYdLlSlw2K7zUVVzu1PD3ByYjHWErmb/68vEVqxPLki9NvLyJ
    WWlEs0PpNQvQSBtEtDsU8G8J5KvgSbQZz8K8gadWFYbN2OIoiStMUSXl6Mu+HenP
    9faiEAS2CZBQ5JjuJCU4CDDvqHPbCZ3qBb8Xj2is+BcZy2z37YJ9HfqL+B2f/VNo
    8iaxTs51O89QrXR/knMp9/OjHcsDc+T9iPSk8qcLP7xribY7fjKSpedgfMSKrFfK
    USkCggEBAIOzK/Aw0wOeLeGT0NRHVW0x4RyZUFeQ/U/ImuddIzhsBdgxFZSMGnqZ
    +0/Q7k1X377XNGbbj7p9vOEJw2aqAIzEYmXcgvo+kJO41ah6pp2qQ0FKnonyL80z
    B/oL2693mfrjTCoIGpDdZk0KicKoxfelPdJByNDR8MtWZHyc00OSSD3HLDXAoyiG
    YNsrtEg/KHKGXfEJJNOV0A6wVsaw4rYZ6zP+zT9PWgfDUGzd+HyDZI047PYrLQE/
    h0c529XXSSRFZDeEdAn30Hm5MUWlh85Y2ZSc5Eh0cQ1K1PpJN5/yMnrVDbSO5GmH
    Eqsov2zCnSwfS5C7zfP6ahIhuL8gscU=
    -----END PRIVATE KEY-----
  public.crt: |
    -----BEGIN CERTIFICATE-----
    MIIFcDCCA1gCCQCwj36GPKuvlDANBgkqhkiG9w0BAQsFADB6MQswCQYDVQQGEwJY
    WDESMBAGA1UECAwJU3RhdGVOYW1lMREwDwYDVQQHDAhDaXR5TmFtZTEUMBIGA1UE
    CgwLQ29tcGFueU5hbWUxGzAZBgNVBAsMEkNvbXBhbnlTZWN0aW9uTmFtZTERMA8G
    A1UEAwwIZmFrZS5zc2wwHhcNMjMxMTIxMTYwMzUxWhcNMzMxMTE4MTYwMzUxWjB6
    MQswCQYDVQQGEwJYWDESMBAGA1UECAwJU3RhdGVOYW1lMREwDwYDVQQHDAhDaXR5
    TmFtZTEUMBIGA1UECgwLQ29tcGFueU5hbWUxGzAZBgNVBAsMEkNvbXBhbnlTZWN0
    aW9uTmFtZTERMA8GA1UEAwwIZmFrZS5zc2wwggIiMA0GCSqGSIb3DQEBAQUAA4IC
    DwAwggIKAoICAQDmQCS9f6taTTEyw2dtDjb5nefW6fDzcL0aT3P9PqFtK4xLD91D
    F2xK/+MEia5HuG4c6FXF/RC6vLM6LvRf9/smfQaLZ/E6bE2WxnWgtcF6RgTO4FqJ
    Qp8er6jEkQyNCS+CPhzbOXwUUc1u2GUeQKGVkILyRH6k+zt/PWM1yvv7VS4XZFR9
    HpfEggNj3SE4q5K57kg4VE3RMY1ImHNf9+UNeIu37TI37wABBO3zzTAM3hyoP0xB
    lg+4r3ZBKW8XzGNpUcR64w+HuF9h0t0UN+tMVWKeJ3plSoysgOhIaEuqg6sWf6zQ
    /6rvxjj97rCPuyDS28O4HFpXs6j4vwgcsa037Z+6+km1+3ci3IRdN8IVZoV7zjS4
    IZrVTGvp9tfSIuhR3KFrTRaiJGsjZttllixmVr0JZSC87p0t/ASmcPrTy75xxBL8
    hI1uQwjUsxKtjl6tqmd8bQRAfh1nJaQeib/7uGRI82K53qaMjjQ9dvJbyeOOw+qJ
    cF6DxI2LPPil9fvmjctEATXWESa7ZmeOGqyvzMQRrZL5TXu3o8T+oj4MpZrLrSDJ
    Lym2RhYf2GssG1MJankxDAWAbMYM/QwfOxVWSExdgPjh2NtJDRgBNluPGdlbOzlw
    fad7MwGm+s+eNKW5JYWKIigDg+cj5rdX367+qLgN7IqRpr5teNUf45683wIDAQAB
    MA0GCSqGSIb3DQEBCwUAA4ICAQDhxrcH24BvAnWp0RMlGkl/dHOMOpz1mjvYJGJX
    JMmlO+UQM3+eMmyxQx/+qiDiosvjxOZ2jdHAFH0yvSb/2Co2c7T9+k4BnQh8c9bL
    s3PnmFSSuaZaKMSgl8FKIP4Q2FVfNyF9zp0lawPx+PVB+ZuOoEVJau4rUbyQ1TmW
    RsjuDpi5S8+0C6Z2K5WtqbvZCbyoLYcEAF3Zp502s4Nqx1SvUyEYE/YNfLYs7hcq
    0/zPR0YQkgV5KDRHug1/471c5UhSwvdGvpvNFNS8v7reXGfcQD8Sbw1ju+OMHIne
    hCdCXxq2karTOA64C0IOYPJpsgWnJt7FxsXrzrUEnbODrVof7qQvP7GU53lyxFZM
    1hjprEUEJGadzrPC/1tnmWauqgx4iK+3sfhUBQJcDnxukd8GSd3QmiMpSy/OQGJB
    3X2am/rWqfnkDTmSTDFHX5ojtGqOW/I0XYZdmC4SKW1tr8AlMOHf2QNL6w1d4gQ9
    Tq9WLM1Q9YE0PjJFll929T0ik3+Pigs7aM2Eb1uPE/pKyAJ7C3yiwKOmGd1Q9Iah
    Xy3EJiTYe8UwzkkHV3kkYxNPZPe2ZmjqvjwywZObmMgk3wpLU1EUqzA8y+7piecN
    gH/j+lbkQw8C9H9gz39/WIADj8Ta8aiyhGgdIBUrKYIAz8iRzRKWrHdSiqybpK13
    Q+PSjg==
    -----END CERTIFICATE-----
---
apiVersion: v1
kind: Secret
metadata:
  name: tutorial-settings
type: service.binding/maven
stringData:
  type: maven
  provider: sample
  settings.xml: |
    <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 https://maven.apache.org/xsd/settings-1.0.0.xsd">
        <profiles>
            <profile>
                <id>profile-test</id>
                <properties>
                    <tomcat.version>9.0.80</tomcat.version>
                </properties>
            </profile>
        </profiles>
    </settings>
---
apiVersion: v1
kind: Secret
metadata:
  name: tutorial-certificates
type: service.binding/ca-certificates
stringData:
  type: ca-certificates
  provider: sample
  public.crt: |
    -----BEGIN CERTIFICATE-----
    MIIFcDCCA1gCCQCwj36GPKuvlDANBgkqhkiG9w0BAQsFADB6MQswCQYDVQQGEwJY
    WDESMBAGA1UECAwJU3RhdGVOYW1lMREwDwYDVQQHDAhDaXR5TmFtZTEUMBIGA1UE
    CgwLQ29tcGFueU5hbWUxGzAZBgNVBAsMEkNvbXBhbnlTZWN0aW9uTmFtZTERMA8G
    A1UEAwwIZmFrZS5zc2wwHhcNMjMxMTIxMTYwMzUxWhcNMzMxMTE4MTYwMzUxWjB6
    MQswCQYDVQQGEwJYWDESMBAGA1UECAwJU3RhdGVOYW1lMREwDwYDVQQHDAhDaXR5
    TmFtZTEUMBIGA1UECgwLQ29tcGFueU5hbWUxGzAZBgNVBAsMEkNvbXBhbnlTZWN0
    aW9uTmFtZTERMA8GA1UEAwwIZmFrZS5zc2wwggIiMA0GCSqGSIb3DQEBAQUAA4IC
    DwAwggIKAoICAQDmQCS9f6taTTEyw2dtDjb5nefW6fDzcL0aT3P9PqFtK4xLD91D
    F2xK/+MEia5HuG4c6FXF/RC6vLM6LvRf9/smfQaLZ/E6bE2WxnWgtcF6RgTO4FqJ
    Qp8er6jEkQyNCS+CPhzbOXwUUc1u2GUeQKGVkILyRH6k+zt/PWM1yvv7VS4XZFR9
    HpfEggNj3SE4q5K57kg4VE3RMY1ImHNf9+UNeIu37TI37wABBO3zzTAM3hyoP0xB
    lg+4r3ZBKW8XzGNpUcR64w+HuF9h0t0UN+tMVWKeJ3plSoysgOhIaEuqg6sWf6zQ
    /6rvxjj97rCPuyDS28O4HFpXs6j4vwgcsa037Z+6+km1+3ci3IRdN8IVZoV7zjS4
    IZrVTGvp9tfSIuhR3KFrTRaiJGsjZttllixmVr0JZSC87p0t/ASmcPrTy75xxBL8
    hI1uQwjUsxKtjl6tqmd8bQRAfh1nJaQeib/7uGRI82K53qaMjjQ9dvJbyeOOw+qJ
    cF6DxI2LPPil9fvmjctEATXWESa7ZmeOGqyvzMQRrZL5TXu3o8T+oj4MpZrLrSDJ
    Lym2RhYf2GssG1MJankxDAWAbMYM/QwfOxVWSExdgPjh2NtJDRgBNluPGdlbOzlw
    fad7MwGm+s+eNKW5JYWKIigDg+cj5rdX367+qLgN7IqRpr5teNUf45683wIDAQAB
    MA0GCSqGSIb3DQEBCwUAA4ICAQDhxrcH24BvAnWp0RMlGkl/dHOMOpz1mjvYJGJX
    JMmlO+UQM3+eMmyxQx/+qiDiosvjxOZ2jdHAFH0yvSb/2Co2c7T9+k4BnQh8c9bL
    s3PnmFSSuaZaKMSgl8FKIP4Q2FVfNyF9zp0lawPx+PVB+ZuOoEVJau4rUbyQ1TmW
    RsjuDpi5S8+0C6Z2K5WtqbvZCbyoLYcEAF3Zp502s4Nqx1SvUyEYE/YNfLYs7hcq
    0/zPR0YQkgV5KDRHug1/471c5UhSwvdGvpvNFNS8v7reXGfcQD8Sbw1ju+OMHIne
    hCdCXxq2karTOA64C0IOYPJpsgWnJt7FxsXrzrUEnbODrVof7qQvP7GU53lyxFZM
    1hjprEUEJGadzrPC/1tnmWauqgx4iK+3sfhUBQJcDnxukd8GSd3QmiMpSy/OQGJB
    3X2am/rWqfnkDTmSTDFHX5ojtGqOW/I0XYZdmC4SKW1tr8AlMOHf2QNL6w1d4gQ9
    Tq9WLM1Q9YE0PjJFll929T0ik3+Pigs7aM2Eb1uPE/pKyAJ7C3yiwKOmGd1Q9Iah
    Xy3EJiTYe8UwzkkHV3kkYxNPZPe2ZmjqvjwywZObmMgk3wpLU1EUqzA8y+7piecN
    gH/j+lbkQw8C9H9gz39/WIADj8Ta8aiyhGgdIBUrKYIAz8iRzRKWrHdSiqybpK13
    Q+PSjg==
    -----END CERTIFICATE-----
---
# Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tutorial-service-account
  namespace: default
secrets:
  - name: tutorial-registry-credentials
  - name: tutorial-certificates
  - name: tutorial-settings
imagePullSecrets:
  - name: tutorial-registry-credentials
