# Service Account
# Registry credentials to allow push image
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tutorial-service-account
  namespace: default
secrets:
  - name: tutorial-registry-credentials
imagePullSecrets:
  - name: tutorial-registry-credentials
