apiVersion: v1
kind: Secret
metadata:
  name: tutorial-settings
type: service.binding/maven
stringData:
  type: maven
  provider: sample
  settings.xml: |
    <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 https://maven.apache.org/xsd/settings-1.0.0.xsd">
        <profiles>
            <profile>
                <id>profile-test</id>
                <properties>
                    <tomcat.version>9.0.80</tomcat.version>
                </properties>
            </profile>
        </profiles>
    </settings>
---
apiVersion: v1
kind: Secret
metadata:
  name: tutorial-certificates
type: service.binding/ca-certificates
stringData:
  type: ca-certificates
  provider: sample
  superusercom.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDrDCCAzGgAwIBAgISA1PDZBSv8vrkUtJJWxWXH6upMAoGCCqGSM49BAMDMDIx
    CzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MQswCQYDVQQDEwJF
    MTAeFw0yMzA5MTgyMzU0NThaFw0yMzEyMTcyMzU0NTdaMB8xHTAbBgNVBAMMFCou
    bWV0YS5zdXBlcnVzZXIuY29tMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEYGof
    NyJntffErnRGAXCaNXb68H35q2P/Jd4ZQWO408qp0QuBpeQrWQPdTE4avsmW/q4H
    XBoE1lvMaz4BvBgFKKOCAjgwggI0MA4GA1UdDwEB/wQEAwIHgDAdBgNVHSUEFjAU
    BggrBgEFBQcDAQYIKwYBBQUHAwIwDAYDVR0TAQH/BAIwADAdBgNVHQ4EFgQU1hJj
    PoH6JeEz8JM95SHwsgLuWW8wHwYDVR0jBBgwFoAUWvPtK/w2wjd5uVIw6lRvz1XL
    LqwwVQYIKwYBBQUHAQEESTBHMCEGCCsGAQUFBzABhhVodHRwOi8vZTEuby5sZW5j
    ci5vcmcwIgYIKwYBBQUHMAKGFmh0dHA6Ly9lMS5pLmxlbmNyLm9yZy8wPwYDVR0R
    BDgwNoIUKi5tZXRhLnN1cGVydXNlci5jb22CDyouc3VwZXJ1c2VyLmNvbYINc3Vw
    ZXJ1c2VyLmNvbTATBgNVHSAEDDAKMAgGBmeBDAECATCCAQYGCisGAQQB1nkCBAIE
    gfcEgfQA8gB3AHoyjFTYty22IOo44FIe6YQWcDIThU070ivBOlejUutSAAABiqru
    58kAAAQDAEgwRgIhAJQr7xAGW3xiaayuVe411YMvaNxaGMR2nC0en65y8rrfAiEA
    8SHfeljvkWNgVYnQVg/BGY/Ipt5yM+8D/rTwOcBC+6wAdwDoPtDaPvUGNTLnVyi8
    iWvJA9PL0RFr7Otp4Xd9bQa9bgAAAYqq7ue1AAAEAwBIMEYCIQC75zwjKB/V7JPa
    KnwQC3iWtNvXAxlIgk9P4CeGD5W7QQIhALftU/GUMmtLkXK7ekZJq54H3ajkOaFu
    Czy/yDgXKdqcMAoGCCqGSM49BAMDA2kAMGYCMQCmesVap3ZgFSXIbeMil8Uk4PY8
    4FXLjJdG4ff1wUj5lc5bywsziMzQNwmUlvM0D6ICMQCOWZusp7gRKx+8RI+5zNAc
    AxYsEvlpbVKr2dFJPqXwfqcaQxxj+DraXEebcoaoNnE=
    -----END CERTIFICATE-----
---
# Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tutorial-service-account
  namespace: default
secrets:
  - name: tutorial-registry-credentials
  - name: tutorial-certificates
  - name: tutorial-settings
imagePullSecrets:
  - name: tutorial-registry-credentials
