apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-spring-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-spring-app
  template:
    metadata:
      labels:
        app: my-spring-app
    spec:
      containers:
        - name: my-spring-app
          image: yoanyo/hello-world:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
---
apiVersion: v1
kind: Service
metadata:
  name: my-spring-app-service
spec:
  selector:
    app: my-spring-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: my-spring-app2
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: my-spring-app2
#   template:
#     metadata:
#       labels:
#         app: my-spring-app2
#     spec:
#       containers:
#         - name: my-spring-app2
#           image: yoanyo/hello-world2:latest
#           ports:
#             - containerPort: 8080
#           env:
#             - name: SPRING_PROFILES_ACTIVE
#               value: "prod"
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: my-spring-app-service2
# spec:
#   selector:
#     app: my-spring-app2
#   ports:
#     - name: http
#       protocol: TCP
#       port: 80
#       targetPort: 8080
# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: my-spring-app3
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: my-spring-app3
#   template:
#     metadata:
#       labels:
#         app: my-spring-app3
#     spec:
#       containers:
#         - name: my-spring-app3
#           image: yoanyo/hello-world3:latest
#           ports:
#             - containerPort: 8080
#           env:
#             - name: SPRING_PROFILES_ACTIVE
#               value: "prod"
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: my-spring-app-service3
# spec:
#   selector:
#     app: my-spring-app3
#   ports:
#     - name: http
#       protocol: TCP
#       port: 80
#       targetPort: 8080
