apiVersion: v1
kind: Secret
metadata:
  name: tutorial-certificates
type: service.binding/ca-certificates
stringData:
  type: ca-certificates
  #provider: sample
  metasupercom.pem: |
    -----BEGIN CERTIFICATE-----
    MIIDrDCCAzGgAwIBAgISA1PDZBSv8vrkUtJJWxWXH6upMAoGCCqGSM49BAMDMDIx
    CzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MQswCQYDVQQDEwJF
    MTAeFw0yMzA5MTgyMzU0NThaFw0yMzEyMTcyMzU0NTdaMB8xHTAbBgNVBAMMFCou
    bWV0YS5zdXBlcnVzZXIuY29tMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEYGof
    NyJntffErnRGAXCaNXb68H35q2P/Jd4ZQWO408qp0QuBpeQrWQPdTE4avsmW/q4H
    XBoE1lvMaz4BvBgFKKOCAjgwggI0MA4GA1UdDwEB/wQEAwIHgDAdBgNVHSUEFjAU
    BggrBgEFBQcDAQYIKwYBBQUHAwIwDAYDVR0TAQH/BAIwADAdBgNVHQ4EFgQU1hJj
    PoH6JeEz8JM95SHwsgLuWW8wHwYDVR0jBBgwFoAUWvPtK/w2wjd5uVIw6lRvz1XL
    LqwwVQYIKwYBBQUHAQEESTBHMCEGCCsGAQUFBzABhhVodHRwOi8vZTEuby5sZW5j
    ci5vcmcwIgYIKwYBBQUHMAKGFmh0dHA6Ly9lMS5pLmxlbmNyLm9yZy8wPwYDVR0R
    BDgwNoIUKi5tZXRhLnN1cGVydXNlci5jb22CDyouc3VwZXJ1c2VyLmNvbYINc3Vw
    ZXJ1c2VyLmNvbTATBgNVHSAEDDAKMAgGBmeBDAECATCCAQYGCisGAQQB1nkCBAIE
    gfcEgfQA8gB3AHoyjFTYty22IOo44FIe6YQWcDIThU070ivBOlejUutSAAABiqru
    58kAAAQDAEgwRgIhAJQr7xAGW3xiaayuVe411YMvaNxaGMR2nC0en65y8rrfAiEA
    8SHfeljvkWNgVYnQVg/BGY/Ipt5yM+8D/rTwOcBC+6wAdwDoPtDaPvUGNTLnVyi8
    iWvJA9PL0RFr7Otp4Xd9bQa9bgAAAYqq7ue1AAAEAwBIMEYCIQC75zwjKB/V7JPa
    KnwQC3iWtNvXAxlIgk9P4CeGD5W7QQIhALftU/GUMmtLkXK7ekZJq54H3ajkOaFu
    Czy/yDgXKdqcMAoGCCqGSM49BAMDA2kAMGYCMQCmesVap3ZgFSXIbeMil8Uk4PY8
    4FXLjJdG4ff1wUj5lc5bywsziMzQNwmUlvM0D6ICMQCOWZusp7gRKx+8RI+5zNAc
    AxYsEvlpbVKr2dFJPqXwfqcaQxxj+DraXEebcoaoNnE=
    -----END CERTIFICATE-----
---
# Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tutorial-service-account
  namespace: default
secrets:
- name: tutorial-registry-credentials
- name: tutorial-certificates
imagePullSecrets:
- name: tutorial-registry-credentials
---
# Cluster Store
apiVersion: kpack.io/v1alpha2
kind: ClusterStore
metadata:
  name: store-java
spec:
  sources:
  - image: gcr.io/paketo-buildpacks/java
---
# Cluster Stack
apiVersion: kpack.io/v1alpha2
kind: ClusterStack
metadata:
  name: stack-java
spec:
  id: "io.buildpacks.stacks.jammy"
  buildImage:
    image: "paketobuildpacks/build-jammy-base:latest"
  runImage:
    image: "paketobuildpacks/run-jammy-base:latest"
  # Download images from a private repo
  # serviceAccountRef:
  #   name: private
  #   namespace: private
---
# Builder
apiVersion: kpack.io/v1alpha2
kind: Builder
metadata:
  name: java-builder
  namespace: default
spec:
  serviceAccountName: tutorial-service-account
  tag: yoanyo/buildpack
  stack:
    name: stack-java
    kind: ClusterStack
  store:
    name: store-java
    kind: ClusterStore
  order:
  - group:
    - id: paketo-buildpacks/java
---
# Image
apiVersion: kpack.io/v1alpha2
kind: Image
metadata:
  name: tutorial-image
  namespace: default
spec:
  tag: yoanyo/hello-world
  serviceAccountName: tutorial-service-account
  builder:
    name: java-builder
    kind: Builder
  source:
    git:
      url: https://github.com/juanjmerono/hello-world
      revision: main
  build:
    env:
      - name: BP_MAVEN_BUILD_ARGUMENTS
        value: --batch-mode -Dtomcat.version=9.0.82 --no-transfer-progress package
      - name: BP_JVM_VERSION
        value: "11"      
    sevices:
      - name: tutorial-certificates
        kind: Secret
        apiVersion: v1
# ---
# # Image
# apiVersion: kpack.io/v1alpha2
# kind: Image
# metadata:
#   name: tutorial-image2
#   namespace: default
# spec:
#   tag: yoanyo/hello-world2
#   serviceAccountName: tutorial-service-account
#   builder:
#     name: java-builder
#     kind: Builder
#   source:
#     git:
#       url: https://github.com/juanjmerono/hello-world
#       revision: main
#   build:
#     # Connecting service bindings
#     sevices:
#       - name: tutorial-certificates
#         kind: Secret
#         apiVersion: v1
# ---
# # Image
# apiVersion: kpack.io/v1alpha2
# kind: Image
# metadata:
#   name: tutorial-image3
#   namespace: default
# spec:
#   tag: yoanyo/hello-world3
#   serviceAccountName: tutorial-service-account
#   builder:
#     name: java-builder
#     kind: Builder
#   source:
#     registry:
#       image: yoanyo/hello-world-src:latest
