# Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tutorial-service-account
  namespace: default
secrets:
- name: tutorial-registry-credentials
imagePullSecrets:
- name: tutorial-registry-credentials
---
# Cluster Store
apiVersion: kpack.io/v1alpha2
kind: ClusterStore
metadata:
  name: default
spec:
  sources:
  - image: gcr.io/paketo-buildpacks/java
---
# Alternative Cluster Store
apiVersion: kpack.io/v1alpha2
kind: ClusterStore
metadata:
  name: alternative
spec:
  sources:
  #- image: gcr.io/paketo-buildpacks/java
  - image: gcr.io/paketo-buildpacks/apache-tomcat
  - image: gcr.io/paketo-buildpacks/apache-tomee
  - image: gcr.io/paketo-buildpacks/azure-application-insights
  - image: gcr.io/paketo-buildpacks/amazon-corretto
  - image: gcr.io/paketo-buildpacks/ca-certificates
  - image: gcr.io/paketo-buildpacks/clojure-tools
  - image: gcr.io/paketo-buildpacks/yarn
  - image: gcr.io/paketo-buildpacks/node-engine
  - image: gcr.io/paketo-buildpacks/datadog
  - image: gcr.io/paketo-buildpacks/dist-zip
  - image: gcr.io/paketo-buildpacks/encrypt-at-rest
  - image: gcr.io/paketo-buildpacks/environment-variables
  - image: gcr.io/paketo-buildpacks/executable-jar
  - image: gcr.io/paketo-buildpacks/google-stackdriver
  - image: gcr.io/paketo-buildpacks/gradle
  - image: gcr.io/paketo-buildpacks/image-labels
  - image: gcr.io/paketo-buildpacks/jattach
  - image: gcr.io/paketo-buildpacks/java-memory-assistant
  - image: gcr.io/paketo-buildpacks/leiningen
  - image: gcr.io/paketo-buildpacks/liberty
  - image: gcr.io/paketo-buildpacks/maven
  - image: gcr.io/paketo-buildpacks/procfile
  - image: gcr.io/paketo-buildpacks/sbt
  - image: gcr.io/paketo-buildpacks/spring-boot
  - image: gcr.io/paketo-buildpacks/syft
  - image: gcr.io/paketo-buildpacks/watchexec
---
# Cluster Stack
apiVersion: kpack.io/v1alpha2
kind: ClusterStack
metadata:
  name: base
spec:
  id: "io.buildpacks.stacks.bionic"
  buildImage:
    image: "paketobuildpacks/build-bionic-base:latest"
  runImage:
    image: "paketobuildpacks/run-bionic-base:latest"
---
# Cluster Stack
apiVersion: kpack.io/v1alpha2
kind: ClusterStack
metadata:
  name: base2
spec:
  id: "io.buildpacks.stacks.jammy"
  buildImage:
    image: "paketobuildpacks/build-jammy-base:latest"
  runImage:
    image: "paketobuildpacks/run-jammy-base:latest"
---
# Builder
apiVersion: kpack.io/v1alpha2
kind: Builder
metadata:
  name: my-builder
  namespace: default
spec:
  serviceAccountName: tutorial-service-account
  tag: yoanyo/buildpack
  stack:
    name: base
    kind: ClusterStack
  store:
    name: default
    kind: ClusterStore
  order:
  - group:
    - id: paketo-buildpacks/java
---
# Altrnative Builder
apiVersion: kpack.io/v1alpha2
kind: Builder
metadata:
  name: alt-builder
  namespace: default
spec:
  serviceAccountName: tutorial-service-account
  tag: yoanyo/buildpack2
  stack:
    name: base2
    kind: ClusterStack
  store:
    name: alternative
    kind: ClusterStore
  order:
  - group:
    - id: paketo-buildpacks/ca-certificates
      optional: true
    - id: paketo-buildpacks/amazon-corretto
      optional: false
    - id: paketo-buildpacks/yarn
      optional: true
    - id: paketo-buildpacks/node-engine
      optional: true
    - id: paketo-buildpacks/syft
      optional: true
    - id: paketo-buildpacks/leiningen
      optional: true
    - id: paketo-buildpacks/clojure-tools
      optional: true
    - id: paketo-buildpacks/gradle
      optional: true
    - id: paketo-buildpacks/maven
      optional: true
    - id: paketo-buildpacks/sbt
      optional: true
    - id: paketo-buildpacks/watchexec
      optional: true
    - id: paketo-buildpacks/executable-jar
      optional: true
    - id: paketo-buildpacks/apache-tomcat
      optional: true
    - id: paketo-buildpacks/apache-tomee
      optional: true
    - id: paketo-buildpacks/liberty
      optional: true
    - id: paketo-buildpacks/dist-zip
      optional: true
    - id: paketo-buildpacks/spring-boot
      optional: true
    - id: paketo-buildpacks/procfile
      optional: true
    - id: paketo-buildpacks/jattach
      optional: true
    - id: paketo-buildpacks/azure-application-insights
      optional: true
    - id: paketo-buildpacks/google-stackdriver
      optional: true
    - id: paketo-buildpacks/datadog
      optional: true
    - id: paketo-buildpacks/java-memory-assistant
      optional: true
    - id: paketo-buildpacks/encrypt-at-rest
      optional: true
    - id: paketo-buildpacks/environment-variables
      optional: true
    - id: paketo-buildpacks/image-labels
      optional: true
---
# Image
apiVersion: kpack.io/v1alpha2
kind: Image
metadata:
  name: tutorial-image
  namespace: default
spec:
  tag: yoanyo/hello-world
  serviceAccountName: tutorial-service-account
  builder:
    name: my-builder
    kind: Builder
  source:
    git:
      url: https://github.com/juanjmerono/hello-world
      revision: main
---
# Image
apiVersion: kpack.io/v1alpha2
kind: Image
metadata:
  name: tutorial-image2
  namespace: default
spec:
  tag: yoanyo/hello-world2
  serviceAccountName: tutorial-service-account
  builder:
    name: alt-builder
    kind: Builder
  source:
    git:
      url: https://github.com/juanjmerono/hello-world
      revision: main
---
# Image
apiVersion: kpack.io/v1alpha2
kind: Image
metadata:
  name: tutorial-image3
  namespace: default
spec:
  tag: yoanyo/hello-world3
  serviceAccountName: tutorial-service-account
  builder:
    name: my-builder
    kind: Builder
  source:
    registry:
      image: yoanyo/hello-world-src:latest
